### ISSUE TITLE
Week 3 Plan

### ISSUE THREAD

**Issue by pali1460** [pali1460/Group4ProjectRepo#29]
The plan for Week 3 of the project

Okay, fine, it's more like Week 4.

- #37 
- #38 
- #41 
- #50

**Comment by AbbyHaines** [comment]
- #43 
- #44 
- #45 
- #49

**Comment by Flextwaft** [comment]
- #48

**Comment by pali1460** [comment]
- #51

**Comment by pali1460** [comment]
Complete.
